version: '3'
services:
  ws:
    build:
      context: ./
      dockerfile: ws.dockerfile
    container_name: ws
    ports:
     - "3001:3001"
    volumes:
     - .:/usr/src/app
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true
     - MONGODB_URI=mongodb+srv://Rolando:rolando@cluster0-e8mbp.mongodb.net/test?retryWrites=true
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: app
    ports:
     - "3000:3000"
     - "35729:35729"
    volumes:
     - ./client:/usr/src/app
    environment:
     - NODE_ENV=development
     - CHOKIDAR_USEPOLLING=true
    links:
     - ws